#!/bin/sh

# relaunching DWM if the binary changes, otherwise bail
#csum=""
#new_csum=$(sha1sum $(which dwm))
#while true
#do
#    if [ "$csum" != "$new_csum" ]
#    then
#         csum=$new_csum
#         dwm 2>/dev/null
#    else
#         exit 0
#    fi
#    new_csum=$( sha1sum $(which dwm))
#    sleep 1
#done

while true; do
    dwm 2>/dev/null
done

